fantasy:
  nfl:
    stats-resource: stats/2015/2015.csv
    roster:
      size: 9
      limits:
        QB: 1
        RB: 2
        WR: 2
        TE: 2
        K: 1
        D: 1
    roster-generator:
      brute-force:
        debug: false
        number-to-return: 5
      max-points:
        debug: false
      value:
        debug: false