fantasy:
  nfl:
    stats-resource: stats/stats.csv
    excluded-teams: [ 'xSF', 'xPIT', 'xLV', 'xDAL', 'xPHI', 'xARI' ]
    roster:
      size: 9
      positions:
        "QB": 1
        "RB": 2
        "WR": 2
        "TE": 1
        "[FX,RB,WR,TE]": 1
        "K": 1
        "D": 1
    roster-generator:
      brute-force:
        debug: true
        number-to-return: 5
      brute-recursive:
        debug: true
      max-points:
        debug: true
      value:
        debug: true